"""baseline schema

Revision ID: 44e30fbeb985
Revises: 
Create Date: 2026-07-25 20:18:39.305321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e30fbeb985'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('ttl', sa.Float(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('chat_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embed_cache',
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=False),
    sa.Column('vector_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('text_hash')
    )
    op.create_table('ingest_log',
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('lawd_cd', sa.String(length=10), nullable=False),
    sa.Column('deal_ym', sa.String(length=6), nullable=False),
    sa.Column('fetched_at', sa.Float(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('endpoint', 'category', 'lawd_cd', 'deal_ym')
    )
    op.create_table('region_codes',
    sa.Column('region_name', sa.String(length=50), nullable=False),
    sa.Column('lawd_code', sa.String(length=10), nullable=False),
    sa.Column('sido', sa.String(length=30), nullable=False),
    sa.Column('sigungu', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('region_name')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('lawd_cd', sa.String(length=10), nullable=False),
    sa.Column('deal_ym', sa.String(length=6), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('area_pyeong', sa.Float(), nullable=True),
    sa.Column('per_sqm', sa.BigInteger(), nullable=True),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('year_built', sa.String(length=10), nullable=True),
    sa.Column('dong', sa.String(length=50), nullable=True),
    sa.Column('apt_name', sa.String(length=100), nullable=True),
    sa.Column('deal_year', sa.String(length=10), nullable=True),
    sa.Column('deal_month', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tx_apt', 'transactions', ['lawd_cd', 'apt_name'], unique=False)
    op.create_index('idx_tx_key', 'transactions', ['endpoint', 'category', 'lawd_cd', 'deal_ym'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('created', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_created'), 'activity', ['created'], unique=False)
    op.create_index(op.f('ix_activity_user_id'), 'activity', ['user_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_created'), 'history', ['created'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_created'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_activity_user_id'), table_name='activity')
    op.drop_index(op.f('ix_activity_created'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_tx_key', table_name='transactions')
    op.drop_index('idx_tx_apt', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('region_codes')
    op.drop_table('ingest_log')
    op.drop_table('embed_cache')
    op.drop_table('chat_chunks')
    op.drop_table('api_cache')
    # ### end Alembic commands ###
