// 격리 API 주소를 인자로 받고 임시 Next 서버에서 CSV 수입 흐름을 검증한다.
const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');
const {spawn,spawnSync}=require('node:child_process');const net=require('node:net');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
(async()=>{
 const backend=process.argv[2];assert.ok(backend?.startsWith('http://'));
 const report={scenario:'매물 등록부터 변경 재검토와 재선택',started_at:new Date().toISOString(),status:'running',checks:[],boundaries:['매물 수집 성공·접근 제한·대기 응답은 고정 입력','실제 AVM 정확도와 대화 품질은 별도 평가']};
 const checked=(name)=>report.checks.push({name,status:'passed'});
 const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
 const root=path.resolve(__dirname,'..');const log=fs.openSync(path.join(root,'evaluation-results/listing-next.log'),'w');
 const server=spawn(process.execPath,[path.join(root,'frontend/node_modules/next/dist/bin/next'),'dev','--hostname','127.0.0.1','--port',String(port)],{cwd:path.join(root,'frontend'),env:{...process.env,NEXT_PUBLIC_API_URL:backend},stdio:['ignore',log,log],windowsHide:true});
 let browser,context,registered=false;
 try{
  browser=await chromium.launch(process.env.E2E_BROWSER==='chromium'?{headless:true}:{channel:'chrome',headless:true});context=await browser.newContext({baseURL:`http://127.0.0.1:${port}`});
  for(let i=0;i<60;i++){try{if((await context.request.get('/api/auth/me')).status()===401)break;}catch{}await new Promise(r=>setTimeout(r,1000));}
  const reg=await context.request.post('/api/auth/register',{data:{email:`listing-browser-${Date.now()}@example.com`,password:'listing-browser-12345',name:'매물 수입 검증'}});assert.equal(reg.status(),201);registered=true;
  checked('가입과 세션 쿠키');
  const page=await context.newPage();page.setDefaultTimeout(60000);await page.goto('/listings');
  await page.getByRole('heading',{name:'매물 보관함',exact:true}).waitFor();
  await page.getByText('여러 매물 등록 (CSV)',{exact:true}).click();
  const header='external_id,name,property_type,transaction_type,address,legal_region_code,area_sqm,asking_price,confirmed_at,status';
  const confirmed=new Date(Date.now()-3600000).toISOString();
  const csv=header+'\nfixture-1,브라우저 검증용 가상 매물,apartment,purchase,서울특별시 강남구 역삼동 123,1168010100,84,700000000,'+confirmed+',active\n';
  await page.getByPlaceholder('제공 중개업소 또는 직접 등록').fill('검증용 가상 출처');
  await page.getByLabel('매물 CSV 파일').setInputFiles({name:'listings.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
  await page.getByRole('button',{name:'검증·미리보기'}).click();await page.getByText('총 1행 · 오류 0건 · 주의 0건',{exact:true}).waitFor();
  assert.equal((await(await context.request.get('/api/listings')).json()).total,0);
  await page.getByRole('button',{name:'검증된 자료 저장'}).click();await page.getByRole('heading',{name:'브라우저 검증용 가상 매물',exact:true}).waitFor();
  let list=await(await context.request.get('/api/listings')).json();assert.equal(list.total,1);assert.equal(list.items[0].asking_price,700000000);
  checked('CSV 입력·검증·DB 저장');
  await page.getByLabel('지역 (서울)',{exact:true}).selectOption('1168000000');
  await page.getByLabel('법정동',{exact:true}).selectOption('1168010100');
  await page.getByRole('button',{name:'검색',exact:true}).click();await page.getByText(/총 1건/).waitFor();
  await page.getByRole('button',{name:'매수 후보 저장'}).click();await page.getByRole('link',{name:'케이스 보기'}).waitFor();
  const cases=await(await context.request.get('/api/cases')).json();const detail=await(await context.request.get(`/api/cases/${cases.items[0].id}`)).json();assert.equal(detail.properties[0].asking_price,700000000);
  checked('매물 후보 연결');
  const bad=csv.replace('700000000','7억');await page.getByLabel('매물 CSV 파일').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from(bad)});
  await page.getByRole('button',{name:'검증·미리보기'}).click();await page.getByText(/오류가 있어 저장하지 않습니다/).waitFor();assert.ok(await page.getByRole('button',{name:'검증된 자료 저장'}).isDisabled());
  assert.equal((await(await context.request.get('/api/listings')).json()).total,1);
  await page.getByRole('button',{name:'변경 이력'}).click();await page.getByRole('heading',{name:'최근 변경 이력 (최대 100건)'}).waitFor();
  await page.getByText('매물 등록 · 링크로 불러오기 또는 직접 입력',{exact:true}).click();
  assert.equal(await page.getByRole('link',{name:'네이버 부동산 지도 열기 (새 탭)',exact:true}).getAttribute('href'),'https://fin.land.naver.com/map');
  await page.getByLabel('네이버 매물 링크').fill('https://example.com/articles/123456');
  await page.getByLabel('매물 이름',{exact:true}).fill('링크 등록 검증용 가상 매물');
  await page.getByLabel('확인한 주소').fill('서울특별시 강남구 역삼동 123');
  await page.getByLabel('확인한 면적 (㎡)').fill('84');
  await page.getByLabel('확인한 호가 (원)').fill('800000000');
  await page.getByLabel('원문 확인 일시 (현재 기기 시간대)').fill(new Date(Date.now()-3600000).toISOString().slice(0,16));
  await page.getByRole('button',{name:'관심 매물 등록',exact:true}).click();
  await page.getByText('네이버페이 부동산의 HTTPS 매물 링크를 입력해주세요.',{exact:true}).waitFor();
  assert.equal((await(await context.request.get('/api/listings')).json()).total,1);
  await page.getByLabel('네이버 매물 링크').fill('https://fin.land.naver.com/articles/123456');
  await page.getByRole('button',{name:'관심 매물 등록',exact:true}).click();
  await page.getByRole('heading',{name:'링크 등록 검증용 가상 매물',exact:true}).waitFor();
  list=await(await context.request.get('/api/listings')).json();
  const linked=list.items.find(item=>item.external_id==='123456');
  assert.equal(linked.asking_price,800000000);assert.equal(linked.status,'unknown');assert.equal(linked.source_url,'https://fin.land.naver.com/articles/123456');
  // 실제 수집 성공 여부와 구분해서, 고정 응답으로 추출값 검토 UI를 검증한다.
  const observation={observation_id:999,external_id:'987654',source_url:'https://fin.land.naver.com/articles/987654',requested_at:Date.now()/1000,fetched_at:Date.now()/1000,outcome:'observed',message:'고정 응답 검증',fields:{name:'추출 검증용 가상 매물',address:'서울특별시 강남구 역삼동 123',area_sqm:84,asking_price:900000000,transaction_type:'purchase'}};
  await page.route('**/api/listings/collection/**',route=>{
    const url=route.request().url();
    return route.fulfill({json:url.includes('/history?')?{items:[observation]}:url.endsWith('/jobs')?{job_id:'fixture'}:{status:'done',result:observation}});
  });
  await page.getByLabel('수집할 매물 링크').fill(observation.source_url);
  await page.getByRole('button',{name:'원문 수집·재확인',exact:true}).click();
  await page.getByRole('button',{name:'추출값을 아래 등록 폼에 적용',exact:true}).click();
  assert.equal(await page.getByLabel('매물 이름',{exact:true}).inputValue(),observation.fields.name);
  assert.equal(await page.getByLabel('확인한 호가 (원)').inputValue(),'900000000');
  assert.equal(await page.getByLabel('확인한 거래 상태').inputValue(),'unknown');
  assert.equal(await page.getByLabel('원문 확인 일시 (현재 기기 시간대)').inputValue(),'');
  // 오류 화면으로 이동했더라도 접근 제한으로 안내하고 자동 재요청하지 않는다.
  observation.observation_id=1000;observation.outcome='blocked';observation.fields={};observation.message='네이버가 원문 접근을 제한했습니다.';
  observation.reason_code='naver_http_429';observation.upstream_status=429;observation.retry_at=Date.now()/1000+900;
  await page.getByRole('button',{name:'원문 수집·재확인',exact:true}).click();
  await page.getByText('접근 제한으로 정보를 확인하지 못했습니다. 매물 삭제나 거래 종료를 뜻하지 않습니다.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'원문 수집·재확인',exact:true}).isDisabled(),true);
  await page.getByRole('button',{name:'이 링크로 수동 등록',exact:true}).click();
  assert.equal(await page.getByLabel('네이버 매물 링크',{exact:true}).inputValue(),observation.source_url);
  assert.equal(await page.getByLabel('확인한 호가 (원)').inputValue(),'');
  checked('접근 제한 결과·재시도 대기·추측값 없는 수동 등록');
  await page.reload();
  await page.getByText('매물 등록 · 링크로 불러오기 또는 직접 입력',{exact:true}).click();
  await page.unroute('**/api/listings/collection/**');
  let attempts=0;
  await page.route('**/api/listings/collection/jobs',route=>{attempts++;return route.fulfill({status:429,headers:{'Retry-After':'900'},json:{detail:'네이버 원문 수집을 잠시 쉬고 있습니다. 자동 재시도하지 않습니다.'}});});
  await page.getByLabel('수집할 매물 링크').fill(observation.source_url);
  await page.getByRole('button',{name:'원문 수집·재확인',exact:true}).click();
  await page.getByRole('button',{name:'이 링크로 수동 등록',exact:true}).click();
  assert.equal(await page.getByRole('button',{name:'원문 수집·재확인',exact:true}).isDisabled(),true);
  assert.equal(await page.getByLabel('네이버 매물 링크',{exact:true}).inputValue(),observation.source_url);
  assert.equal(await page.getByLabel('확인한 호가 (원)').inputValue(),'');
  assert.equal(attempts,1);
  checked('서비스 공통 대기 HTTP 429·재요청 방지·수동 등록');
  await page.goto(`/cases/${cases.items[0].id}/comparison`);
  await page.getByRole('button',{name:'이 후보를 최종 선택'}).click();
  await page.getByPlaceholder(/예: 예산/).fill('최초 확인 가격을 기준으로 선택');
  await page.getByRole('button',{name:'선택 저장'}).click();
  await page.getByText('최종 선택과 근거가 저장되었습니다.').waitFor();
  checked('초기 비교와 근거를 포함한 선택');
  const changed=csv.replace('700000000', '750000000').replace(confirmed, new Date().toISOString());
  const changedImport=await context.request.post('/api/listings/import',{data:{source_name:'검증용 가상 출처',csv_text:changed,commit:true}});
  assert.equal(changedImport.status(),200);assert.equal((await changedImport.json()).updated,1);
  const changedCase=await(await context.request.get(`/api/cases/${cases.items[0].id}`)).json();
  assert.equal(changedCase.properties[0].asking_price,700000000);
  assert.equal(changedCase.properties[0].source_status.status,'changed');
  assert.equal((await context.request.post(`/api/cases/${cases.items[0].id}/decision`,{data:{property_id:detail.properties[0].id,reason:'변경 전 자료로 다시 선택'}})).status(),422);
  await page.goto(`/cases/${cases.items[0].id}`);
  await page.getByText('원본 매물 재확인 필요',{exact:true}).waitFor();
  await page.getByRole('button',{name:'확인한 변경사항 반영'}).click();
  await page.getByText('이전 최종 선택이 해제되었습니다.',{exact:false}).waitFor();
  const reviewed=await(await context.request.get(`/api/cases/${cases.items[0].id}`)).json();
  assert.equal(reviewed.selected_property_id,null);
  assert.equal(reviewed.properties[0].asking_price,750000000);
  assert.equal(reviewed.properties[0].source_status.status,'current');
  assert.equal(reviewed.properties[0].source_reviews[0].previous_decision.reason,'최초 확인 가격을 기준으로 선택');
  checked('원본 변경 반영·선택 해제·과거 근거 보존');
  await page.reload();
  await page.getByText('매물 변경·이전 판단 기록 1건').waitFor();
  await page.goto(`/cases/${cases.items[0].id}/comparison`);
  await page.getByText('저장 당시와 동일',{exact:true}).waitFor();
  await page.getByRole('button',{name:'이 후보를 최종 선택'}).click();
  await page.getByPlaceholder(/예: 예산/).fill('변경된 가격을 확인하고 다시 선택');
  await page.getByRole('button',{name:'선택 저장'}).click();
  await page.getByText('최종 선택과 근거가 저장되었습니다.').waitFor();
  await page.reload();
  await page.getByText('저장 당시와 동일',{exact:true}).waitFor();
  checked('재선택 뒤 새로고침 복원');
  await page.screenshot({path:path.join(root,'evaluation-results/listing-import-browser.png'),fullPage:true});
  report.status='passed';
  console.log('PASS CSV → candidate → initial selection → source change → apply and reopen → selection → refresh');
 }catch(e){report.status='failed';report.error=e instanceof Error?e.message:String(e);throw e;}finally{
  report.finished_at=new Date().toISOString();
  fs.writeFileSync(path.join(root,'evaluation-results/decision-flow-browser.json'),JSON.stringify(report,null,2));
  try{if(registered)assert.equal((await context.request.delete('/api/auth/me')).status(),200);}finally{
   if(browser)await browser.close();if(server.pid){if(process.platform==='win32')spawnSync('taskkill',['/PID',String(server.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});else server.kill('SIGTERM');}fs.closeSync(log);
  }
 }
})().catch(e=>{console.error(e.message);process.exitCode=1;});
